baseURL = 'https://superflash41.github.io/thss/'
publishDir = "../docs"
languageCode = 'en-us'
title = "Thesis Research Notes"
hideTitle = true
theme = "typo"

[params]
# meta description
description = "Summaries and insights from the papers I'm reading."
author = "Saymon Nicho"
dateFormat = "May 14, 2025"

# appearance
theme = "light"
# colorPalette = "catpuccin"
pagerSize = 10

# intro on main page
homeIntroTitle = "Thesis Research Notes"
homeIntroContent = """
This is a collection of notes and summaries from papers I reviewed as
part of a systematic literature review for my undergraduate thesis in Computer Science.

The thesis explores a neuro-symbolic solution to the ARC-AGI benchmark, using
lightweight language models and efficient symbolic representation techniques.

These notes aim to extract key insights and technical details relevant to
intelligence, abstract reasoning, generalization, and neuro-symbolic AI.

For comments or suggestions, please reach out to me on LinkedIn or GitHub.
"""

# collection to display on home
homeCollectionTitle = "Papers"
homeCollection = "papers"

# social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/saymon-nicho/"

[[params.social]]
name = "github"
url = "https://www.github.com/superflash41"

# [[params.social]]
# name = "gmail"
# url = "mailto:saymon@example.com"

# [[params.social]]
# name = "x"
# url = "https://twitter.com/saymon_nicho"

# main menu pages
[[params.menu]]
name = "home"
url = "/thss"

[[params.menu]]
name = "papers"
url = "/thss/papers"
